spring:
  profiles:
    active: postgres
  data:
    rest:
      base-path: /api
---
spring:
  profiles: local
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.format_sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  profiles: postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.format_sql: true
  datasource:
    hikari:
      maximum-pool-size: 4
    password: pgadmin
    url: jdbc:postgresql://localhost:5432/kalpha
    username: pgadmin
